export const TOGGLE_DROPDOWN = "TOGGLE_DROPDOWN";
export const SUPER_ADMIN_LOGOUT = "SUPER_ADMIN_LOGOUT";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const FETCH_PURCHASES_REQUEST = 'FETCH_PURCHASES_REQUEST';
export const FETCH_PURCHASES_SUCCESS = 'FETCH_PURCHASES_SUCCESS';
export const FETCH_PURCHASES_FAILURE = 'FETCH_PURCHASES_FAILURE';


// src/redux/actions/purchaseStockActionTypes.js
export const SUBMIT_PURCHASE_REQUEST = 'SUBMIT_PURCHASE_REQUEST';
export const SUBMIT_PURCHASE_SUCCESS = 'SUBMIT_PURCHASE_SUCCESS';
export const SUBMIT_PURCHASE_FAILURE = 'SUBMIT_PURCHASE_FAILURE';

export const FETCH_PENDING_USERS_REQUEST = "FETCH_PENDING_USERS_REQUEST";
export const FETCH_PENDING_USERS_SUCCESS = "FETCH_PENDING_USERS_SUCCESS";
export const FETCH_PENDING_USERS_FAILURE = "FETCH_PENDING_USERS_FAILURE";

export const APPROVE_USER_REQUEST = "APPROVE_USER_REQUEST";
export const APPROVE_USER_SUCCESS = "APPROVE_USER_SUCCESS";
export const APPROVE_USER_FAILURE = "APPROVE_USER_FAILURE";

export const REJECT_USER_REQUEST = "REJECT_USER_REQUEST";
export const REJECT_USER_SUCCESS = "REJECT_USER_SUCCESS";
export const REJECT_USER_FAILURE = "REJECT_USER_FAILURE";

export const FETCH_LOGS_REQUEST = "FETCH_LOGS_REQUEST";
export const FETCH_LOGS_SUCCESS = "FETCH_LOGS_SUCCESS";
export const FETCH_LOGS_FAILURE = "FETCH_LOGS_FAILURE";

export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";

// temp

export const TEMP_STOCK_SUBMIT_REQUEST = "TEMP_STOCK_SUBMIT_REQUEST";
export const TEMP_STOCK_SUBMIT_SUCCESS = "TEMP_STOCK_SUBMIT_SUCCESS";
export const TEMP_STOCK_SUBMIT_FAILURE = "TEMP_STOCK_SUBMIT_FAILURE";

export const TEMP_STOCK_FETCH_REQUEST = 'TEMP_STOCK_FETCH_REQUEST';
export const TEMP_STOCK_FETCH_SUCCESS = 'TEMP_STOCK_FETCH_SUCCESS';
export const TEMP_STOCK_FETCH_FAILURE = 'TEMP_STOCK_FETCH_FAILURE';
