export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const FETCH_PURCHASES_REQUEST = 'FETCH_PURCHASES_REQUEST';
export const FETCH_PURCHASES_SUCCESS = 'FETCH_PURCHASES_SUCCESS';
export const FETCH_PURCHASES_FAILURE = 'FETCH_PURCHASES_FAILURE';


// src/redux/actions/purchaseStockActionTypes.js
export const SUBMIT_PURCHASE_REQUEST = 'SUBMIT_PURCHASE_REQUEST';
export const SUBMIT_PURCHASE_SUCCESS = 'SUBMIT_PURCHASE_SUCCESS';
export const SUBMIT_PURCHASE_FAILURE = 'SUBMIT_PURCHASE_FAILURE';
