export const TOGGLE_DROPDOWN = "TOGGLE_DROPDOWN";
export const SUPER_ADMIN_LOGOUT = "SUPER_ADMIN_LOGOUT";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE";

export const FETCH_PENDING_USERS_REQUEST = "FETCH_PENDING_USERS_REQUEST";
export const FETCH_PENDING_USERS_SUCCESS = "FETCH_PENDING_USERS_SUCCESS";
export const FETCH_PENDING_USERS_FAILURE = "FETCH_PENDING_USERS_FAILURE";

export const APPROVE_USER_REQUEST = "APPROVE_USER_REQUEST";
export const APPROVE_USER_SUCCESS = "APPROVE_USER_SUCCESS";
export const APPROVE_USER_FAILURE = "APPROVE_USER_FAILURE";

export const REJECT_USER_REQUEST = "REJECT_USER_REQUEST";
export const REJECT_USER_SUCCESS = "REJECT_USER_SUCCESS";
export const REJECT_USER_FAILURE = "REJECT_USER_FAILURE";

export const FETCH_LOGS_REQUEST = "FETCH_LOGS_REQUEST";
export const FETCH_LOGS_SUCCESS = "FETCH_LOGS_SUCCESS";
export const FETCH_LOGS_FAILURE = "FETCH_LOGS_FAILURE";

export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";

// temp

export const TEMP_STOCK_SUBMIT_REQUEST = "TEMP_STOCK_SUBMIT_REQUEST";
export const TEMP_STOCK_SUBMIT_SUCCESS = "TEMP_STOCK_SUBMIT_SUCCESS";
export const TEMP_STOCK_SUBMIT_FAILURE = "TEMP_STOCK_SUBMIT_FAILURE";

export const TEMP_STOCK_FETCH_REQUEST = 'TEMP_STOCK_FETCH_REQUEST';
export const TEMP_STOCK_FETCH_SUCCESS = 'TEMP_STOCK_FETCH_SUCCESS';
export const TEMP_STOCK_FETCH_FAILURE = 'TEMP_STOCK_FETCH_FAILURE';

export const FETCH_STOCK_REQUEST = "FETCH_STOCK_REQUEST";
export const FETCH_STOCK_SUCCESS = "FETCH_STOCK_SUCCESS";
export const FETCH_STOCK_FAILURE = "FETCH_STOCK_FAILURE";

export const QMPURCHASE_SUBMIT_REQUEST = "QMPURCHASE_SUBMIT_REQUEST";
export const QMPURCHASE_SUBMIT_SUCCESS = "QMPURCHASE_SUBMIT_SUCCESS";
export const QMPURCHASE_SUBMIT_FAILURE = "QMPURCHASE_SUBMIT_FAILURE";

export const FETCH_QM_ISSUE_ENTRIES_REQUEST = "FETCH_QM_ISSUE_ENTRIES_REQUEST";
export const FETCH_QM_ISSUE_ENTRIES_SUCCESS = "FETCH_QM_ISSUE_ENTRIES_SUCCESS";
export const FETCH_QM_ISSUE_ENTRIES_FAILURE = "FETCH_QM_ISSUE_ENTRIES_FAILURE";

export const FETCH_CATEGORIES_REQUEST = "FETCH_CATEGORIES_REQUEST";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_FAILURE = "FETCH_CATEGORIES_FAILURE";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_SUBCATEGORY_SUCCESS = "ADD_SUBCATEGORY_SUCCESS";

export const FETCH_OFFICES_REQUEST = "FETCH_OFFICES_REQUEST";
export const FETCH_OFFICES_SUCCESS = "FETCH_OFFICES_SUCCESS";
export const FETCH_OFFICES_FAILURE = "FETCH_OFFICES_FAILURE";
export const ADD_OFFICE_SUCCESS = "ADD_OFFICE_SUCCESS";
export const DELETE_OFFICE_SUCCESS = "DELETE_OFFICE_SUCCESS";