version: '3.9'

services:
  mongo:
    image: mongo
    container_name: kepaqmis-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./kepaqmis-backend
    container_name: kepaqmis-backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/qmisdb

  frontend:
    build: ./kepaqmis
    container_name: kepaqmis-frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend

volumes:
  mongo-data:
