version: '3.8'

services:
  mongo:
    image: mongo
    container_name: qmis-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./kepaqmis-backend
    container_name: qmis-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/qmisdb
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo

  frontend:
    build: ./kepaqmis
    container_name: qmis-frontend
    ports:
      - "3000:3000"  # CRA runs on 3000 inside container
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  mongo-data:
